// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMS6rS326mKVIxJsxBdJdk2TyX_OFoa0s',
    appId: '1:441126540998:web:3aa85d8c0547b0300d29c7',
    messagingSenderId: '441126540998',
    projectId: 'tixioapp-b5073',
    authDomain: 'tixioapp-b5073.firebaseapp.com',
    storageBucket: 'tixioapp-b5073.firebasestorage.app',
    measurementId: 'G-NKXGYB6FFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRK4_U9DpJ3WCwnZI9dw5ca8nY3Pv-dc',
    appId: '1:441126540998:android:b9d7b639b08164bd0d29c7',
    messagingSenderId: '441126540998',
    projectId: 'tixioapp-b5073',
    storageBucket: 'tixioapp-b5073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16YU0SH_wUYO-8Ph_3_nlSgCW9wIIzPw',
    appId: '1:441126540998:ios:608a86da1826885d0d29c7',
    messagingSenderId: '441126540998',
    projectId: 'tixioapp-b5073',
    storageBucket: 'tixioapp-b5073.firebasestorage.app',
    iosClientId:
        '441126540998-mapq3ogt31dnao66ni3sdbmeoj7io626.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUtsApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA16YU0SH_wUYO-8Ph_3_nlSgCW9wIIzPw',
    appId: '1:441126540998:ios:608a86da1826885d0d29c7',
    messagingSenderId: '441126540998',
    projectId: 'tixioapp-b5073',
    storageBucket: 'tixioapp-b5073.firebasestorage.app',
    iosClientId:
        '441126540998-mapq3ogt31dnao66ni3sdbmeoj7io626.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUtsApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMS6rS326mKVIxJsxBdJdk2TyX_OFoa0s',
    appId: '1:441126540998:web:3002a55014ce71060d29c7',
    messagingSenderId: '441126540998',
    projectId: 'tixioapp-b5073',
    authDomain: 'tixioapp-b5073.firebaseapp.com',
    storageBucket: 'tixioapp-b5073.firebasestorage.app',
    measurementId: 'G-0H3BRWENBN',
  );
}
